name: download and process

#on: [push]
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.0' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install matplotlib
          
      - name: execute py script 
        run: |
          python src/script.py


      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1.6.0
        with:
          version: "1.6.4"
      - name: "processing"
        run: |
          julia --project=@. -e "using Pkg; Pkg.instantiate();"
          julia src/data_organization.jl
          julia src/main.jl
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "update data" -a
          cd ..
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  